let userName;
let userScore;
const champ = document.getElementById('champ');
const accueil = document.getElementById('id-accueil');
const boulet = document.getElementById('oui');
const clicker = document.getElementById('clicker');
const sous_accueil = document.getElementById('id-sous-accueil');
const sur_toad = document.getElementById('sur-champi-rouge');
const toad = document.getElementById('champi-rouge');
const score = document.getElementById('text-piece');
const bonus_card = document.getElementById('bonus-card');
const scoreboard_html = document.getElementById('id-scoreboard');
const settings = document.getElementById('id-setting-card');
const cpt1 = document.getElementById('cpt1');
const cpt2 = document.getElementById('cpt2');
const cpt3 = document.getElementById('cpt3');
const price1 = document.getElementById('price1');
const price2 = document.getElementById('price2');
const price3 = document.getElementById('price3');
const bo_achat1 = document.getElementById('bonus1');
const bo_achat2 = document.getElementById('bonus2');
const bo_achat3 = document.getElementById('bonus3');
const id_card_setting = document.getElementById('id-card-setting');
const id_img_setting = document.getElementById('id-setting-img');
const id_croix_setting = document.getElementById('id-croix-setting');
const pseudo_setting = document.getElementById('setting-pseudo');
const skin_img = document.getElementsByClassName('all-skin');
const skinRouge = document.getElementById('champi-rouge');
const skinRose = document.getElementById('champi-rose');
const skinCyan = document.getElementById('champi-cyan');
const skinBee = document.getElementById('champi-bee');
const skinOr = document.getElementById('champi-or');
const actu = document.getElementById('actu');
const total = document.getElementById('total');
const precedent = document.getElementById('precedent');
const suivant = document.getElementById('suivant');
var lesPages = document.getElementsByClassName('leader-page');
const succes1 = document.getElementById('id-s-1');
const succes2 = document.getElementById('id-s-2');
const succes3 = document.getElementById('id-s-3');
const succes4 = document.getElementById('id-s-4');
const suc1 = document.getElementById('sucess1');
const suc2 = document.getElementById('sucess2');
const suc3 = document.getElementById('sucess3');
const suc4 = document.getElementById('sucess4');
const champiSkin = document.getElementsByClassName('champi-skin');
const allScore = document.getElementById('allScore');
const allClic = document.getElementById('allClic');
const allMoneySpend = document.getElementById('allMoneySpend');
const allMoney = document.getElementById('allMoney');
const restart = document.getElementById('restart');
const bgVideo = document.getElementById('background-video');
const goToScore = document.getElementById('goToScore');
let restartProof = false;
let ok1 = false;
let ok2 = false;
let ok3 = false;
let ok4 = false;
var id_du_click;
let pseudo;
let blaze;
let bonus1_price = 100;
let bonus2_price = 100;
let bonus3_price = 10000;
let bonus1_cpt = 0;
let bonus2_cpt = 0;
let bonus3_cpt = 0;
let piece = 0;
let highScore = 0;
let highClick = 0;
let highMoneySpend = 0;
let highMoneyMoney = 0;
let userScoreTest;
let temps = 0;
let ajout_temps = 1;
let click = 1;
let nbr_page = 0;
let nbr_score;
let var_actu = 1;
let maFonctionSeconde;



// Pour les interval

